include ../../../make.inc

libname=libtnsp_ext

file := \
tensors.o \
tensor_tools.o

all:	$(file)
	(ar rc $(libname).a *.o ;)

%.o:	source/%.f90
	$(FC) $(FFLAGS) -o $@ -c $(<)
clean:
	rm -rf *.o *.mod *.a
