lat_contract_type – TNSG
lat_contract_type Subroutine
37 statements
Source File
public subroutine lat_contract_type(Tout, T1, T2, G1, G2)
Arguments
Type Intent Optional Attributes Name
type(tensor), intent(inout) :: Tout
type(tensor), intent(inout) :: T1
type(tensor), intent(inout) :: T2
type(group), intent(inout) :: G1
type(group), intent(inout) :: G2
Calls
Contents
None
Call graph
lat_contract_type calls contract, wc_error_stop
wc_error_stop calls wc_error_stop_mess1, wc_error_stop_nomess, wc_error_stop_mess2
wc_error_stop_mess1 calls wc_outpicture, write_message
wc_error_stop_nomess calls wc_outpicture
wc_error_stop_mess2 calls wc_outpicture, write_message
wc_outpicture calls write_message