percent_end – TNSG
percent_end Subroutine
14 statements
Source File
public subroutine percent_end(words_in)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: words_in
Calls
Contents
None
Call graph
percent_end calls wc_error_stop
wc_error_stop calls wc_error_stop_mess2, wc_error_stop_mess1, wc_error_stop_nomess
wc_error_stop_mess2 calls writemess, wc_outpicture
wc_error_stop_mess1 calls writemess, wc_outpicture
wc_error_stop_nomess calls wc_outpicture
wc_outpicture calls writemess