percent – TNSG
percent Subroutine
24 statements
Source File
public subroutine percent(words_in, perc_in, step_)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: words_in
real(kind=8), intent(in) :: perc_in
real(kind=8), intent(in), optional :: step_
Calls
Contents
None
Call graph
percent calls wc_error_stop
wc_error_stop calls wc_error_stop_mess2, wc_error_stop_mess1, wc_error_stop_nomess
wc_error_stop_mess2 calls writemess, wc_outpicture
wc_error_stop_mess1 calls writemess, wc_outpicture
wc_error_stop_nomess calls wc_outpicture
wc_outpicture calls writemess