test_same_type – TNSG
test_same_type Function
15 statements
Source File
public function test_same_type(T, mpi_comm) result(res)
Arguments
Type Intent Optional Attributes Name
type(tensor), intent(in) :: T
integer, intent(in) :: mpi_comm
Return Value integer
Calls
Called by
Contents
None
Call graph
test_same_type calls mpi_allreduce, mpi_bcast
wc_reduce_tensor calls test_same_type
wc_allreduce_tensor calls test_same_type