test_same_length – TNSG
test_same_length Function
15 statements
Source File
public function test_same_length(T, mpi_comm) result(res)
Arguments
Type Intent Optional Attributes Name
type(tensor), intent(in) :: T
integer, intent(in) :: mpi_comm
Return Value integer
Calls
Called by
Contents
None
Call graph
test_same_length calls mpi_allreduce, mpi_bcast
wc_reduce_tensor calls test_same_length
wc_allreduce_tensor calls test_same_length