wc_allreduce_Tensor – TNSG
wc_allreduce_Tensor Subroutine
97 statements
Source File
public subroutine wc_allreduce_Tensor(inTensor, outTensor, op, MPIcommon, ierr)
Arguments
Type Intent Optional Attributes Name
type(Tensor), intent(in), target :: inTensor
type(Tensor), intent(inout), target :: outTensor
integer, intent(in) :: op
integer, intent(in), optional :: MPIcommon
integer, intent(inout) :: ierr
Calls
Contents
None
Call graph
wc_allreduce_tensor calls mpi_comm_size, mpi_allreduce, wc_error_stop, test_same_type, test_same_length, test_same_tensor, mpi_comm_rank, test_not_empty
wc_error_stop calls wc_error_stop_mess1, wc_error_stop_nomess, wc_error_stop_mess2
test_same_type calls mpi_allreduce, mpi_bcast
test_same_length calls mpi_allreduce, mpi_bcast
test_not_empty calls mpi_allreduce
wc_error_stop_mess1 calls write_message, wc_outpicture
wc_error_stop_nomess calls wc_outpicture
wc_error_stop_mess2 calls write_message, wc_outpicture
wc_outpicture calls write_message