wc_error_stop_mess1 – TNSG
wc_error_stop_mess1 Subroutine
10 statements
Source File
public subroutine wc_error_stop_mess1(error_mess)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: error_mess
Calls
Called by
Contents
None
Call graph
wc_error_stop_mess1 calls write_message, wc_outpicture
wc_outpicture calls write_message
wc_error_stop calls wc_error_stop_mess1
percent_end calls wc_error_stop
lat_contract_type calls wc_error_stop
wc_reduce_tensor calls wc_error_stop
percent calls wc_error_stop
wc_allreduce_tensor calls wc_error_stop