wc_error_stop_mess2 – TNSG
wc_error_stop_mess2 Subroutine
11 statements
Source File
public subroutine wc_error_stop_mess2(error_pos, error_mess)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: error_pos
character(len=*), intent(in) :: error_mess
Calls
Called by
Contents
None
Call graph
wc_error_stop_mess2 calls writemess, wc_outpicture
wc_outpicture calls writemess
wc_error_stop calls wc_error_stop_mess2
percent calls wc_error_stop
lat_contract_type calls wc_error_stop
percent_end calls wc_error_stop