write_message – TNSG
write_message Subroutine
5 statements
Source File
public subroutine write_message(message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message
Called by
Contents
None
Call graph
set_output_log_tnsg calls write_message
wc_error_stop_mess1 calls write_message, wc_outpicture
wc_error_stop_mess2 calls write_message, wc_outpicture
wc_outpicture calls write_message
wc_error_stop_nomess calls wc_outpicture
wc_error_stop calls wc_error_stop_mess1, wc_error_stop_mess2, wc_error_stop_nomess
lat_contract_type calls wc_error_stop
wc_reduce_tensor calls wc_error_stop
wc_allreduce_tensor calls wc_error_stop
percent calls wc_error_stop
percent_end calls wc_error_stop