COMPLEX(8) FUNCTION ZDOTU1(N,ZX,INCX,ZY,INCY)
implicit none
      
	INTEGER::INCX,INCY,N
	COMPLEX(8)::ZX((N-1)*INCX+1),ZY((N-1)*INCY+1)
	COMPLEX(8)::ZDOTU
	EXTERNAL::ZDOTU
	INTEGER I,IX,IY

#if BAD_ZDU
	IF (N<0) RETURN
	IF (INCX==1 .AND. INCY==1) THEN
		ZDOTU1 = ZDOTU1 +sum(ZX(1:N)*ZY(1:N))
	ELSE
		ZDOTU1 = ZDOTU1 +sum(ZX(1:(N-1)*INCX+1:INCX)*ZY(1:(N-1)*INCY+1:INCY))
	END IF
#else
	ZDOTU1=ZDOTU(N,ZX,INCX,ZY,INCY)
#endif

END FUNCTION
