str – TNSG
str Interface
15 statements
Source File
public interface str
Called by
Contents
Module Procedures
int2str int_ary2str flt2str flt_ary2str dbl2str dbl_ary2str com2str com_ary2str dcom2str dcom_ary2str logi2str logi_ary2str str_ary2str
Module Procedures
private function int2str(inte) result(str)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: inte
Return Value character(len=:), allocatable
private function int_ary2str(nums, split) result(str2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nums(:)
character(len=1), intent(in), optional :: split
Return Value character(len=:), allocatable
private function flt2str(num, digit) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=4), intent(in) :: num
integer, intent(in), optional :: digit
Return Value character(len=:), allocatable
private function flt_ary2str(nums, split) result(str2)
Arguments
Type Intent Optional Attributes Name
real(kind=4), intent(in) :: nums(:)
character(len=1), intent(in), optional :: split
Return Value character(len=:), allocatable
private function dbl2str(num, digit_) result(str2)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: num
integer, intent(in), optional :: digit_
Return Value character(len=:), allocatable
private function dbl_ary2str(nums, split) result(str2)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: nums(:)
character(len=1), intent(in), optional :: split
Return Value character(len=:), allocatable
private function com2str(num, digit) result(str)
Arguments
Type Intent Optional Attributes Name
complex, intent(in) :: num
integer, intent(in), optional :: digit
Return Value character(len=:), allocatable
private function com_ary2str(nums, split) result(str2)
Arguments
Type Intent Optional Attributes Name
complex(kind=4), intent(in) :: nums(:)
character(len=*), intent(in), optional :: split
Return Value character(len=:), allocatable
private function dcom2str(num, digit) result(str)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(in) :: num
integer, intent(in), optional :: digit
Return Value character(len=:), allocatable
private function dcom_ary2str(nums, split) result(str2)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(in) :: nums(:)
character(len=*), intent(in), optional :: split
Return Value character(len=:), allocatable
private function logi2str(num) result(str)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: num
Return Value character(len=:), allocatable
private function logi_ary2str(nums, split) result(str2)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: nums(:)
character(len=*), intent(in), optional :: split
Return Value character(len=:), allocatable
private function str_ary2str(nums, split) result(str2)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: nums(:)
character(len=1), intent(in), optional :: split
Return Value character(len=:), allocatable
Call graph
str_date_time calls str
str_date_time_ calls str
timer_print calls str