wc_error_stop – TNSG
wc_error_stop Interface
5 statements
Source File
public interface wc_error_stop
Calls
Called by
Contents
Module Procedures
wc_error_stop_mess2 wc_error_stop_mess1 wc_error_stop_nomess
Module Procedures
public subroutine wc_error_stop_mess2(error_pos, error_mess)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: error_pos
character(len=*), intent(in) :: error_mess
public subroutine wc_error_stop_mess1(error_mess)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: error_mess
public subroutine wc_error_stop_nomess()
Arguments
None
Call graph
wc_error_stop calls wc_error_stop_mess1, wc_error_stop_nomess, wc_error_stop_mess2
wc_error_stop_mess1 calls write_message, wc_outpicture
wc_error_stop_nomess calls wc_outpicture
wc_error_stop_mess2 calls write_message, wc_outpicture
wc_outpicture calls write_message
percent_end calls wc_error_stop
lat_contract_type calls wc_error_stop
wc_reduce_tensor calls wc_error_stop
percent calls wc_error_stop
wc_allreduce_tensor calls wc_error_stop